name: Linux Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ninja
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y ninja-build
          ninja --version

      - name: Configure (Release)
        shell: bash
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release

      - name: Smoke test (help)
        continue-on-error: true
        shell: bash
        run: |
          ./build/dataset_cli --help || true

