name: Windows Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSVC (x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install Ninja
        shell: pwsh
        run: |
          choco install ninja -y
          ninja --version

      - name: Configure (Release)
        shell: pwsh
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl

      - name: Build
        shell: pwsh
        run: |
          cmake --build build --config Release

      - name: Smoke test (help)
        continue-on-error: true
        shell: pwsh
        run: |
          .\build\dataset_cli.exe --help
